networks:
  roblox-network:
    external: false

volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:17.5
    container_name: db
    hostname: db
    restart: no
#    command: -c max_connections=265 -c shared_buffers=512MB -c work_mem=4MB -c maintenance_work_mem=64MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c statement_timeout=5000 -c bgwriter_delay=200ms -c bgwriter_lru_maxpages=100 -c bgwriter_lru_multiplier=2.0
    command: -c max_connections=265 -c shared_buffers=512MB -c wal_writer_delay=10ms -c commit_delay=0 -—Å synchronous_commit=on
    ports:
      - "5432:5432"
    networks:
      - roblox-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data:rw
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roblox_test
    shm_size: 512mb
    cpus: 4
    mem_limit: 2GB
    mem_reservation: 512mb
    logging:
      options:
        max-size: 50m

#  app:
#    build: .
#    cpus: 4
#    mem_limit: 512M
#    mem_reservation: 256M
