CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL PRIMARY KEY,
    balance INTEGER NOT NULL DEFAULT 0 CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS cron_locks (
    name TEXT PRIMARY KEY,
    locked_by TEXT NOT NULL,
    locked_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS cron_history (
    id SERIAL PRIMARY KEY,
    task TEXT,
    server TEXT,
    status TEXT,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS cron_worker (
    server TEXT PRIMARY KEY,
    count_tasks INTEGER NOT NULL DEFAULT 0,
    "createdAt"  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
